name: BuildAll

on:
  workflow_dispatch:
    inputs:
      dartversion:
        description: 'Dart SDK stable version'
        required: true
        default: '2.13.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push buildimage
        id: docker_build1
        uses: docker/build-push-action@v2.4.0
        with:
          file: ./at-buildimage/Dockerfile
          build-args: DART_VERSION={{ github.event.inputs.dartversion }}
          push: true
          tags: |
            atsigncompany/buildimage:automated
            atsigncompany/buildimage:GHA_${{ github.run_number }}
            atsigncompany/buildimage:${{ github.event.inputs.dartversion }}
          platforms: |
            linux/amd64
            linux/arm64/v8
      -
        name: Build and push runimage
        id: docker_build2
        uses: docker/build-push-action@v2.4.0
        with:
          file: ./at-runimage/Dockerfile
          push: true
          tags: |
            atsigncompany/runimage:automated
            atsigncompany/buildimage:${{ github.event.inputs.dartversion }}
            atsigncompany/runimage:GHA_${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
      -
        name: Build and push dartshowplatform
        id: docker_build3
        uses: docker/build-push-action@v2.4.0
        with:
          file: ./dartshowplatform/Dockerfile
          push: true
          tags: |
            atsigncompany/dartshowplatform:automated
            atsigncompany/dartshowplatform:latest
            atsigncompany/buildimage:${{ github.event.inputs.dartversion }}
            atsigncompany/dartshowplatform:GHA_${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}