name: DartShowPlatform

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.4.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          file: ./dartshowplatform/Dockerfile
          push: true
          tags: |
            atsigncompany/dartshowplatform:automated
            atsigncompany/dartshowplatform:latest
            atsigncompany/dartshowplatform:GHA${{ github.run_number }}
          platforms: |
            linux/amd64
            linux/arm64/v8
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}